#!/usr/bin/env bash
# This script displays information about subdomains of a given domain.

function get_subdomain_info {
    local domain=$1
    local subdomain=$2
    local record=$(dig +short "$subdomain.$domain")
    if [ -n "$record" ]; then
        echo "The subdomain $subdomain is a A record and points to $record"
    else
        echo "The subdomain $subdomain does not exist."
    fi
}

domain=$1
subdomain=$2

if [ -z "$domain" ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

if [ -n "$subdomain" ]; then
    get_subdomain_info "$domain" "$subdomain"
else
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
fi
