#!/usr/bin/env bash
# Configures a new HAProxy as a load balancer on an Ubuntu server

# Update package lists and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy=1.6.*

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAProxy to use roundrobin algorithm for load balancing
cat <<EOL | sudo tee -a /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 497066-web-01 100.25.130.62:80 check
    server 497066-web-02 34.234.204.119:80 check
EOL

# Restart HAProxy to apply the new configuration
sudo service haproxy restart

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
