#!/usr/bin/env bash
# This script installs and configures HAProxy to distribute traffic between web-01 and web-02
# using a round-robin algorithm.

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
haproxy_cfg="/etc/haproxy/haproxy.cfg"

sudo bash -c "cat > $haproxy_cfg" <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 497066-web-01 100.25.130.62:80 check
    server 497066-web-02 34.234.204.119:80 check
EOL

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Ensure HAProxy starts on boot
sudo systemctl enable haproxy

echo "HAProxy installation and configuration complete."

