#!/usr/bin/env bash
# This script configures Nginx to listen on port 80
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 0.0.0.0:80 default_server;/g' /etc/nginx/sites-available/default
sudo systemctl restart nginx

