#!/usr/bin/env bash
# Run Nginx as nginx user and listen on port 8080

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
service apache2 stop
service nginx restart
